name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Create .env.test file
        run: echo ${{ secrets.DATABASE_URL }} >> .env.test

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Run ESLint
        run: npm run eslint:check

      - name: Run Prettier
        run: npm run prettier:check

      - name: Run tests with Jest
        run: npm run test
