services:
  postgres:
    image: postgres
    container_name: car-manager-test
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car-manager-test
    ports:
      - "5433:5432"
