name: Server CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Create .env.test file
        run: |
          echo "DATABASE_URL=postgresql://root:password@localhost:5433/car-manager-test" >> server/.env.test
          echo "CLERK_PUBLISHABLE_KEY=${{ secrets.TEST_CLERK_PUBLISHABLE_KEY }}" >> server/.env.test
          echo "CLERK_SECRET_KEY=${{ secrets.TEST_CLERK_SECRET_KEY }}" >> server/.env.test
          echo "NODE_ENV=test" >> server/.env.test

      - name: Install dependencies
        run: npm ci --include=dev
        working-directory: server

      - name: Run ESLint
        run: npm run eslint:check
        working-directory: server

      - name: Run Prettier
        run: npm run prettier:check
        working-directory: server

      - name: Run tests with Jest
        run: npm run test
        working-directory: server

  migrate:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Create .env file
        run: echo "DATABASE_URL=${{ secrets.PRODUCTION_DB_URL }}" >> server/.env

      - name: Install dependencies
        run: npm ci --include=dev
        working-directory: server

      - name: Run migrations
        run: npx prisma migrate deploy
        working-directory: server

      - name: Update prisma client
        run: npx prisma generate
        working-directory: server

      - name: Check Prisma Client files
        run: ls -la node_modules/.prisma
        working-directory: server

      - name: Print Prisma Client Type
        run: cat node_modules/.prisma/client/index.d.ts | grep -A 10 "export type Car"
        working-directory: server

  deploy:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
